# Setup
title: Aurylian
tagline: Being the Future for the Past Decade
url: "https://aurylian.net"
baseurl: ""
permalink: pretty
# paginate: 1

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Aurylian
  url: https://twitter.com/aurylian
  # email: 

# Custom vars
version: Alpha

# Gems
# plugins:
#   - jekyll-gist
#   - jekyll-paginate
#   - jekyll-seo-tag


