# Setup
title: Aurylian
tagline: Gaming Narratives and Narrating Games for 2 x 10**-2 Centuries
url: "https://aurylian.net"
baseurl: ""
permalink: pretty
# paginate: 1

# Gems
# plugins:
#   - jekyll-gist
#   - jekyll-paginate
#   - jekyll-seo-tag


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Aurylian
  url: https://twitter.com/aurylian
  # email: 

# Custom vars
version: Alpha